### ISSUE TITLE
Path Resolving going to computer absolute

### ISSUE THREAD

**Issue by marco-quintella** [elcarim5efil/rollup-plugin-require-context#3]
After updated from version 0.2.0 to 1.0.0 the compiled code changed from

```javascript
var components = 
  (function() {
    var map = {
      './LBtn.vue': $0_0,
'./LCard.vue': $0_1,
'./LIcon.vue': $0_2,

    };
    var req = function req(key) {
      return map[key] || (function() { throw new Error("Cannot find module '" + key + "'.") }());
    };
    req.keys = function() {
      return Object.keys(map);
    };
    return req;
  })();
```

to this

```javascript
var components = 
  (function() {
    var map = {
      'E:/GitHub/ui-land/src/components/LBtn.vue': require_context_module_0_0,
'E:/GitHub/ui-land/src/components/LCard.vue': require_context_module_0_1,
'E:/GitHub/ui-land/src/components/LIcon.vue': require_context_module_0_2,

    };
    var req = function req(key) {
      return map[key] || (function() { throw new Error("Cannot find module '" + key + "'.") }());
    };
    req.keys = function() {
      return Object.keys(map);
    };
    return req;
  })()
;
```

If I roll back to version 0.2.0 it cames back to normal.
The code that is being compiled is:
```javascript
const components = require.context('./components', true, /[a-z0-9]+\.vue$/)
```

I checked the code and seems that it begins after the acorn use in version 1.0.0

**Comment by danielelkington** [comment]
I'm also having this issue - solved by rolling back to version 0.0.2.
